### ISSUE TITLE
Updated TZ Data for version 0.3.52

### ISSUE THREAD

**Issue by raganwald** [tzinfo/tzinfo#104]
We are running `0.3.52` in a Rails 3(!) codebase. We're on a pth to a fresher version fo Rails, but for today, this is what we have.

We'd like to update the timezone data to be current. Our understanding is that the utility provided with `0.3.x` to read the timezone files and generate ruby modules does not work with the current file format.

Is there another way to get `0.3.52` updated to the current data?

**Comment by philr** [comment]
Since 0.3.52 was released (a little over 3 years ago), the 0.3 branch has been updated to handle new tzdata releases.

[Version 0.3.56](https://github.com/tzinfo/tzinfo/releases/tag/v0.3.56) contains the latest time zone data (2019c). You should be able to upgrade from 0.3.52 to 0.3.56 without issue.
