### ISSUE TITLE
could not find gem tzinfo

### ISSUE THREAD

**Issue by XRBologna** [tzinfo/tzinfo#115]
Hi, I'm new to Ruby and I just installed it on my PC ( O.S. Windows 7)Then i installled  Jekyll using the prompt.
When I try to run the server I get this:

:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'tzinfo (~> 1.2) x64-mingw32' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)

**Comment by philr** [comment]
The error is saying that the tzinfo gem isn't available in the Ruby installation you're using to run Jekyll.

I'm not familiar with Jekyll, but I think the `jekyll new my-site` command should have installed the dependencies automatically. You could try running `bundle install` from your site directory. You could also try manually installing the tzinfo and tzinfo-data gems by running:

```
gem install tzinfo -v "~> 1.2"
gem install tzinfo-data
```

If you're still encountering problems then I'd suggest posting on [Jekyll Talk](https://talk.jekyllrb.com/) (since this is a problem with your Jekyll setup and not an issue with tzinfo). If you do post there, some more information about the Ruby version you are using and the commands you're running will probably help with working out what is going on.

**Comment by jakejnx** [comment]
Thanks v much

**Comment by Namrajp** [comment]
Thanks very much.

**Comment by lshreyasharmal** [comment]
Thanks! `bundle install ` in the project directory worked for me.
