### ISSUE TITLE
TZInfo::ZoneinfoDirectoryNotFound in gitlab reconfigure

### ISSUE THREAD

**Issue by Kristin33** [tzinfo/tzinfo#119]
When I am installing gitlab on Ubuntu 16.04, I am stuck on this issue that caused by TZInfo dependency. 
`TZInfo::ZoneinfoDirectoryNotFound: None of the paths included in TZInfo::ZoneinfoDataSource.search_path are validzoneinfo directories.`
`/opt/gitlab/embedded/service/gitlab-rails/config/application.rb:14:in `<top (required)>'`
`/opt/gitlab/embedded/service/gitlab-rails/Rakefile:5:in `require'`
`/opt/gitlab/embedded/service/gitlab-rails/Rakefile:5:in `<top (required)>'`
`/opt/gitlab/embedded/bin/bundle:23:in `load'`
`/opt/gitlab/embedded/bin/bundle:23:in `<main>'`

I referred to the page [https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors](url) and did `gem install tzinfo-data`, but the error still shows up. I am not super familiar with gem and ruby...

I also tried `apt-get install tzdata`, but it seems to have conflicts with my local timezone data. 
`dpkg: error processing archive /var/cache/apt/archives/tzdata_2020a-0ubuntu0.16.04_all.deb (--unpack):`
 `unable to make backup link of './usr/share/zoneinfo/Etc/UTC' before installing new version: Invalid cross-devicelink`

**Comment by philr** [comment]
I'm not familiar with the GitLab installation. If it's a typical Ruby app, then to use tzinfo-data, you'll probably need to edit `/opt/gitlab/embedded/service/gitlab-rails/Gemfile`. You'll either need to add a `gem 'tzinfo-data'` line or remove the `platform` from an existing tzinfo-data line. After editing the Gemfile you'll probably need to run `/opt/gitlab/embedded/bin/bundle install` from the `/opt/gitlab/embedded/service/gitlab-rails` directory.

You mention that you have 'local timezone data'. By the looks of your dpkg error, this is contained within the system `/usr/share/zoneinfo` directory. TZInfo requires the `iso3166.tab` and `zone1970.tab` or `zone.tab` files that are part of the standard distribution (they are installed when running `make install` from the [IANA Timezone Database](https://www.iana.org/time-zones) and included in Ubuntu's tzdata package). It is possible you are missing these files.

To install Ubuntu's tzdata package, you'll probably need to delete your local `/usr/share/zoneinfo` directory first, since this is where the package installs its files.

If you want to use your own local data, then you'll need to obtain copies of these files that are compatible with your time zone data.
