### ISSUE TITLE
Wrong UTC offset for Europe/Dublin

### ISSUE THREAD

**Issue by shaicoleman** [tzinfo/tzinfo#130]
```
$ docker run -it docker.io/ubuntu:20.04  # same issue also with Ubuntu 18.04 & 22.04
```
```
$ apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata=2021e-0ubuntu0.20.04 ruby
$ gem install tzinfo -v=2.0.4
$ irb
> require 'tzinfo'
> TZInfo::Timezone.get('Europe/Dublin').current_period.utc_offset
3600 # should be 0
> TZInfo::Timezone.get('Europe/London').current_period.utc_offset
0 # London and Dublin are in the same timezone. London offset is correct
```
```
$ gem install tzinfo-data -v=1.2021.5 # same issue with tzinfo-data installed
$ irb
> require 'tzinfo'
> require 'tzinfo/data'
> TZInfo::Timezone.get('Europe/Dublin').current_period.utc_offset
3600 # should be 0
```

On CentOS 7 it returns the correct offset, unless tzinfo-data is installed:
```
$ docker run -it docker.io/centos:7
```
```
$ yum install -y ruby
$ gem install tzinfo -v=2.0.4
$ irb
> require 'tzinfo'
> TZInfo::Timezone.get('Europe/Dublin').current_period.utc_offset
0 # correct without tzinfo-data
```
```
$ gem install tzinfo-data -v=1.2021.5
$ irb
> require 'tzinfo'
> require 'tzinfo/data'
> TZInfo::Timezone.get('Europe/Dublin').current_period.utc_offset
3600 # incorrect with tzinfo-data
```

**Comment by philr** [comment]
This isn't a bug.

[Ireland's standard time is UTC+1 with GMT observed in winter](https://github.com/eggert/tz/blob/2021e/europe#L368). Europe/Dublin (since version 2018e of the IANA Time Zone Database) therefore applies negative daylight savings in the winter. [`utc_offset` (aka `base_utc_offset`)](https://rubydoc.info/gems/tzinfo/TZInfo%2FTimezonePeriod:base_utc_offset) is constant at 3600 seconds throughout the year. [`std_offset`](https://rubydoc.info/gems/tzinfo/TZInfo%2FTimezonePeriod:std_offset) is -3600 seconds in winter and 0 in summer.

The CentOS 7 tzdata package is presumably built using the backwards compatible 'rearguard' format. In this format Europe/Dublin is rewritten to apply a more standard positive summer daylight savings time offset.

See also #95.
