### ISSUE TITLE
Rename Europe/Kiev to Europe/Kyiv

### ISSUE THREAD

**Issue by z0rc** [tzinfo/tzinfo#149]
https://mm.icann.org/pipermail/tz-announce/2022-August/000071.html

tzdata renamed `Europe/Kiev` to `Europe/Kyiv` in 2022b release. Also link was added to preserve compatibility https://data.iana.org/time-zones/tzdb-2022b/backward.

What the process for this project to follow this change?

**Comment by z0rc** [comment]
To clarify my request. tzinfo supports `TZInfo::Timezone.get('Europe/Kyiv')` just fine, but all test cases use `Europe/Kiev`. Would it be sufficient to update test cases only?

**Comment by philr** [comment]
The only references to Europe/Kiev within tzinfo are in test fixture files. Those files were based on the 2020d release of the IANA Time Zone database. The Europe/Kiev time zone identifier is not used in the unit tests (or any code).

I've updated the test fixture files to 2023c in commit 9953fc092424d55deaea2dcdf6279943f3495724. That's reduced the number of references to Europe/Kiev in the test fixtures from 6 to 2 and increased the number of references to Europe/Kyiv from 0 to 6. The remaining references are because of the backwards compatible link that's still included in the IANA Time Zone database. That will remain here until after Europe/Kiev is removed upstream (if that ever happens).
