### ISSUE TITLE
Failure/Error: require 'active_support/all', while loading spec_helper.rb

### ISSUE THREAD

**Issue by justpiyoosh** [tzinfo/tzinfo#158]
### Steps to reproduce

```ruby
 Run RSpec tests with the command bundle exec rspec.
```

### Expected behavior
RSpec tests should run successfully without any errors.

### Actual behavior
An error occurs while loading spec_helper.rb with the following message:
```
An error occurred while loading spec_helper.
Failure/Error: require 'active_support/all'

NameError:
  uninitialized constant TZInfo::DateTime
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/tzinfo-2.0.6/lib/tzinfo/datetime_with_offset.rb:19:in `<module:TZInfo>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/tzinfo-2.0.6/lib/tzinfo/datetime_with_offset.rb:6:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/tzinfo-2.0.6/lib/tzinfo.rb:30:in `require_relative'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/tzinfo-2.0.6/lib/tzinfo.rb:30:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/values/time_zone.rb:3:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/core_ext/time/conversions.rb:5:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/core_ext/time/calculations.rb:4:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/core_ext/time.rb:4:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/time.rb:12:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.2.2@engineer.ai/gems/activesupport-7.0.5.1/lib/active_support/all.rb:4:in `<top (required)>'
# ./spec/spec_helper.rb:7:in `<top (required)>'
No examples found.


Finished in 0.00004 seconds (files took 0.47417 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

### System configuration
**Rails version**: 7.0.5.1

**Ruby version**: 3.2.2

Contents of spec/spec_helper.rb:
  ```
 # frozen_string_literal: true

require 'dotenv'
Dotenv.load('.env.test')

require 'rest-client'
require 'active_support/all'
require 'active_record_extended'
require 'capybara/rspec'
require 'database_cleaner/active_record'
require 'selenium/webdriver'
require 'webdrivers/chromedriver'
```

**Comment by philr** [comment]
I've tried to reproduce this in the [philr/tzinfo-issue158](https://github.com/philr/tzinfo-issue158) repository, but everything works as expected for me.

The [line that is failing](https://github.com/tzinfo/tzinfo/blob/d5893c99bbcd842af86023f02a84fac1659b3031/lib/tzinfo/datetime_with_offset.rb#L19) is referencing the [`DateTime`](https://ruby-doc.org/3.2.2/exts/date/DateTime.html) class from the Ruby standard library (from the [date](https://rubygems.org/gems/date) default gem). `'date'` has already been required at this point (on line 4), so the class should be available.

It would seem that something has removed or redefined the default date gem in your Ruby installation. What does `gem list date` output? On Ruby 3.2.3 I see:

```
*** LOCAL GEMS ***

date (3.3.4, default: 3.3.3)
```

If date is missing, you could try installing it. Either add `gem 'date'` to your `Gemfile` or run `gem install date`.

What does running `ruby -r date -e 'p defined? DateTime; p DateTime; p DateTime.now'` output? I see:

```
"constant"
DateTime
#<DateTime: 2024-04-13T17:34:46+01:00 ((2460414j,59686s,375544210n),+3600s,2299161j)>
```

I note from the stack trace that your Ruby installation is in a directory named `ruby-3.2.2@engineer.ai`. It is possible that is something non-standard.

If you can get this to reproduce using a clean, standard Ruby installation then I can look at fixing it. Otherwise I don't think there's anything that can be done?

**Comment by justpiyoosh** [comment]
Hi @philr, thank you very much for your response.
I've found the problem. It looks like we made our own Date class in the lib folder to add some new methods. When ActiveSupport loads and tries to load tzinfo, it hits a line in tzinfo/datetime_with_offset.rb:4
`require 'date'
`
This makes our special date thingy load, and that's when everything starts failing.
After deleting the date.rb file from the lib directory. it's working fine now.
