### ISSUE TITLE
timezone data 2024b changed the format

### ISSUE THREAD

**Issue by darix** [tzinfo/tzinfo#159]
https://lists.iana.org/hyperkitty/list/tz-announce@iana.org/thread/IZ7AO6WRE3W3TWBL5IR6PMQUL433BQIE/

besides changing some data for old timestamps it also changed the format which e.g. required changes in gcc

details here:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116657

**Comment by philr** [comment]
The issue with gcc appears to have been it not handling `%z` in the Zone FORMAT field of the Time Zone Database data files. `%z` was first used in the tzdata main form release in version 2024b, but has been allowed syntax for some time.

Since that's a change to the data files (and not the compiled zoneinfo files), it could only affect the Ruby modules generated from tzdata and distributed in the tzinfo-data gem.

Support for `%z` was added to tzinfo-data's module generation 9 years ago. See tzinfo/tzinfo-data@f39d02fa93de4bb9d2f924cfc57f0e0045a4ecda.

The unit tests for tzinfo-data include a comparison between tzinfo's behaviour and the output from the `zdump` tool (see https://github.com/tzinfo/tzinfo-data/blob/v1.2024.2/test/tc_definitions.rb). The v1.2024.2 release of tzinfo-data (based on 2024b) passed all the tests.

If you've found a problem where tzinfo is not producing the correct output, please could you provide the details?

**Comment by darix** [comment]
Thank you for double checking. since we saw it breaking in a few places (gcc, postgresql testsuite) i thought i would bring it up here as well :)
