### ISSUE TITLE
Unexpected timezone format with options_for_select and simple_form_for in Rails.

### ISSUE THREAD

**Issue by adrianmann** [tzinfo/tzinfo#48]
I am using an `f.select` tag to display a drop down of timezones. However, the format displayed is not what is expected. For example, instead of "Europe/Dublin", I am getting "Europe - Dublin"?

The following placed inside a `simple_form_for` block:
```
<%= f.label :timezone %>
<%= f.select :timezone, options_for_select(TZInfo::Timezone.all.each) %>
```
returns timezones with the unexpected format, whereas a `<select>` tag displays them as expected.

How can I correct this issue so the format is returned in the expected way?

**Comment by philr** [comment]
You are seeing the result of `options_for_select` calling [`TZInfo::Timezone#to_s`](http://www.rubydoc.info/gems/tzinfo/TZInfo/Timezone#to_s-instance_method) on each `Timezone`.

[`TZInfo::Timezone.all_identifiers`](http://www.rubydoc.info/gems/tzinfo/TZInfo/Timezone#all_identifiers-class_method) returns an array of identifiers and could be used instead of `all`:

```ruby
<%= f.select :timezone, options_for_select(TZInfo::Timezone.all_identifiers) %>
```

You could also call [`TZInfo::Timezone#identifier`](http://www.rubydoc.info/gems/tzinfo/TZInfo/Timezone#identifier-instance_method) on each `Timezone`:

```ruby
<%= f.select :timezone, 
      options_from_collection_for_select(TZInfo::Timezone.all, :identifier, :identifier) %>
```

**Comment by adrianmann** [comment]
Thank you!
