### ISSUE TITLE
'CEST' causes TZInfo::InvalidTimezoneIdentifier: Invalid identifier

### ISSUE THREAD

**Issue by wueb** [tzinfo/tzinfo#53]
Time.now.getlocal.zone returns 'CEST' on my system.
This leads to an error when calling TZInfo::Timezone.get(Time.now.getlocal.zone).

Maybe you should add CEST to the list of timezones.

Reproduce with TZInfo::Timezone.get('CEST')
About CEST: http://www.timeanddate.com/time/zones/cest

I am using tzinfo version 1.2.2

**Comment by philr** [comment]
TZInfo only supports (and will only ever support) time zone identifiers that are included in the [IANA Time Zone Database](https://www.iana.org/time-zones). CEST is not a valid Time Zone Database identifier, so you will get a `TZInfo::InvalidTimezoneIdentifier` exception raised if you try and use it.

The IANA Time Zone Database doesn't use abbreviations as identifiers because they are frequently ambiguous. Abbreviations also change twice per year in time zones that observe daylight savings time in summer.

You can use the following code to return all the time zones that are currently using CEST as an abbreviation:

```ruby
TZInfo::Timezone.all.find_all {|tz| tz.current_period.abbreviation == :CEST }
```

**Comment by andsens** [comment]
Just for anybody wondering "how bad it can be". Here is the full list of duplicates/ambiguous timezones from [Wikipedia](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations):

```
ACT (UTC-05, Acre Time)
ACT (UTC+08, ASEAN Common Time (proposed))

AET (UTC+10/UTC+11, Australian Eastern Time)

AMT (UTC-04, Amazon Time (Brazil))
AMT (UTC+04, Armenia Time)

BST (UTC+06, Bangladesh Standard Time)
BST (UTC+11, Bougainville Standard Time)
BST (UTC+01, British Summer Time (British Standard Time from Feb 1968 to Oct 1971))

CDT (UTC-05, Central Daylight Time (North America))
CDT (UTC-04, Cuba Daylight Time)

CST (UTC-06, Central Standard Time (North America))
CST (UTC+08, China Standard Time)
CST (UTC-05, Cuba Standard Time)

CT (UTC-06/UTC-05, Central Time)

ECT (UTC-04, Eastern Caribbean Time (does not recognise DST))
ECT (UTC-05, Ecuador Time)

ET (UTC-05 / UTC-04, Eastern Time (North America))

GST (UTC-02, South Georgia and the South Sandwich Islands Time)
GST (UTC+04, Gulf Standard Time)

IST (UTC+05:30, Indian Standard Time)
IST (UTC+01, Irish Standard Time)
IST (UTC+02, Israel Standard Time)

LHST (UTC+10:30, Lord Howe Standard Time)
LHST (UTC+11, Lord Howe Summer Time)

MST (UTC+08, Malaysia Standard Time)
MST (UTC-07, Mountain Standard Time (North America))

SST (UTC-11, Samoa Standard Time)
SST (UTC+08, Singapore Standard Time)
```
