### ISSUE TITLE
Update 0.3x series with 2016h timezone data

### ISSUE THREAD

**Issue by smlsml** [tzinfo/tzinfo#58]
2016h is out https://www.iana.org/time-zones

http://mm.icann.org/pipermail/tz-announce/2016-October/000042.html

Can we get a 0.3.52 gem with it?

**Comment by philr** [comment]
Can I ask why you need a new 0.3.x release?

I'm not really intending to continue supporting or releasing updates for the old 0.3.x branch. It has now been over three years since TZInfo version 1.0.0 was released. The last version of Rails to require 0.3.x is the now unsupported version 4.0 (Rails 4.1 and later use the latest version of TZInfo).

The 2016h Time Zone Database is available in tzinfo-data v1.2016.8 (which requires `tzinfo >= 1.0.0`).

If you want to build your own update to 0.3.x, you can do so by extracting the IANA Time Zone Database tzdata tarball into the data directory and running `rake build_tz_modules`.

**Comment by MGPalmer** [comment]
I would assume that OP is, like us, stuck on Rails 3.x :/

**Comment by smlsml** [comment]
Our app is still on Rails 3.2 (3.2.22.5) which requires tzinfo 0.3.x (ActiveRecord or ActiveSupport I think). We desperately need to update to a newer version of Rails but that is a huge undertaking due to the size of our app.

I mostly just need the Turkish timezone changes in 2016g. We ship the code server in an on-prem OVA so we have to be diligent about these details.

It would really help us out to get a new version cut.

Hope you can help, many thanks!

Steve


On Oct 27, 2016, at 1:17 PM, Phil Ross <notifications@github.com<mailto:notifications@github.com>> wrote:


Can I ask why you need a new 0.3.x release?

I'm not really intending to continue supporting or releasing updates for the old 0.3.x branch. It has now been over three years since TZInfo version 1.0.0 was released. The last version of Rails to require 0.3.x is the now unsupported version 4.0 (Rails 4.1 and later use the latest version of TZInfo).

The 2016h Time Zone Database is available in tzinfo-data v1.2016.8 (which requires tzinfo >= 1.0.0).

If you want to build your own update to 0.3.x, you can do so by extracting the IANA Time Zone Database tzdata tarball into the data directory and running rake build_tz_modules.

**Comment by philr** [comment]
I taken a look at the download figures for tzinfo 0.3.x gems, calculating [the number of downloads each version has had per day that version was the latest available](https://docs.google.com/spreadsheets/d/1wTNt1y160oQelKwF6H6z2DXD-AjPe8wFQhorEOH510Y/pubchart?oid=1809337773&format=interactive). This statistic shows that usage of 0.3.x is declining, but there are still ~5000 downloads per day of the latest version.

I've just published [v0.3.52](https://github.com/tzinfo/tzinfo/releases/tag/v0.3.52) (based on tzdata 2016h).

I'll carry on doing 0.3.x releases for significant changes to the IANA Time Zone Database for a while longer (but not forever).

**Comment by MGPalmer** [comment]
@philr Thanks a million! I actually managed to hack together our own version (half an hour ago...what are the odds?), but I'm very glad to use the "official" version!
