### ISSUE TITLE
`TZInfo::Country` no information about linked timezones

### ISSUE THREAD

**Issue by davispuh** [tzinfo/tzinfo#71]
I want to get all timezones for specific country, but `TZInfo::Country.zone_identifiers` doesn't return linked timezones.

For example

```ruby
TZInfo::Country.get('SS').zone_identifiers
=> ["Africa/Khartoum"]

TZInfo::Timezone.get('Africa/Juba').canonical_zone.identifier
=> "Africa/Khartoum"
```

Thus, I also want to get `Africa/Juba` for `SS`

Currently seems would need to go over all linked timezones and check their canonical zone against already returned zones.

**Comment by philr** [comment]
Please refer to my comment on #60 (which is the same issue, but talking about Croatia rather than South Sudan).

The IANA Time Zone database [defines `Africa/Khartoum` as the (only) time zone for `SS`](https://github.com/eggert/tz/blob/075ad7016e4519cab9728fd248e79ce50637ddd6/zone1970.tab#L319). TZInfo is just returning the data from the Time Zone database unmodified.

**Comment by davispuh** [comment]
That is based on current status, but in past it was `Africa/Juba`, see [zone.tab](https://github.com/eggert/tz/blob/075ad7016e4519cab9728fd248e79ce50637ddd6/zone.tab#L375)

I'm using TZInfo for processing historical data thus there it would appear as `Africa/Juba` instead of `Africa/Khartoum`

Anyway okay I'll just go over `all_linked_zones` as suggested.
