### ISSUE TITLE
Question: are leap seconds handled correctly?

### ISSUE THREAD

**Issue by aldrinmartoq** [tzinfo/tzinfo#81]
Reading the source code, it seems that leap seconds are ignored. Are they handled somehow? What would happen to a timezone transition if a leap second is added, are those timestamps recalculated?

Thanks!

**Comment by philr** [comment]
The times of transitions are described using Unix time (also known as POSIX time). All the calculations performed by TZInfo are also based on Unix time.

Unix time is defined as the number of seconds that have elapsed since 00:00:00 Coordinated Universal Time (UTC) on 1 January 1970, minus the number of leap seconds that have occurred since (i.e. treating every day as if it were exactly 86,400 seconds long).

Unix time deals with the insertion of a leap second by repeating a Unix time second. If a leap second were to be deleted, a Unix time second would be skipped.

Because Unix time effectively ignores leap seconds, it is not necessary for any adjustments or recalculations to be made when leap seconds are added.
