### ISSUE TITLE
I think you forgot to bump 0.3 version when updated this branch with 2018 data

### ISSUE THREAD

**Issue by tbem** [tzinfo/tzinfo#83]

**Comment by philr** [comment]
Not bumping the version was intentional.

0.3.x was superseded by 1.x nearly 5 years ago. The 0.3 branch is still updated with time zone database releases, but 0.3.x releases are only created sporadically.

Please consider upgrading to the latest TZInfo release (currently 1.2.5). The new version will use either your system zoneinfo files or the tzinfo-data gem as its source of time zone data. A new tzinfo-data release is created for every time zone database release.

If you still need to use 0.3.x and want to remain up to date, you can point bundler at the 0.3 git branch in your Gemfile:

```ruby
gem 'tzinfo', git : 'https://github.com/tzinfo/tzinfo.git', branch: '0.3'
```
