### ISSUE TITLE
Two data issues: Netherlands Antilles and Bouvet Island

### ISSUE THREAD

**Issue by johnnyshields** [tzinfo/tzinfo#85]
1) Country "AN" (Netherlands Antilles) is missing. It's timezone is America/Curacao which is present.

2) Country "BV" (Bouvet Island) is missing its timezone, which is Europe/Oslo.

**Comment by philr** [comment]
These issues relate to the underlying data from the [IANA Time Zone Database](https://www.iana.org/time-zones). They're not actually being caused by tzinfo or tzinfo-data.

Country "AN" Netherlands Antilles [changed to "CW" Curacao](https://github.com/eggert/tz/commit/cb40cb7c3d6e28100814f0d252b103aa6be154f7#diff-1570f0d65d17ac3a8195fe350c53906c) in the version 2011h release of the Time Zone Database. This change brought the database back into line with the ISO 3166 standard. Curacao has since been renamed Curaçao.

Country "BV" (Bouvet Island) has no time zones defined in the Time Zone Database (there are no entries for BV in the [zone1970.tab file](https://github.com/eggert/tz/blob/master/zone1970.tab)). This is presumably because Bouvet Island is uninhabited.

If you want to suggest changes to the Time Zone Database, you should raise them on the [Time Zone Database discussion mailing list](https://mm.icann.org/mailman/listinfo/tz).

**Comment by johnnyshields** [comment]
thank you!
