### ISSUE TITLE
tzinfo 2.0.0 availability

### ISSUE THREAD

**Issue by jmettraux** [tzinfo/tzinfo#86]
Hello,

thanks again for https://github.com/floraison/et-orbi/pull/9

when do you think tzinfo 2.0.0 will be available?

I realize it contains a TZInfo::LocalTime class and, from what I've seen so far, it completely overlaps my https://github.com/floraison/et-orbi (please tell me if I'm wrong).

I'd be very happy to put et-orbi in the garage and use tzinfo directly from https://github.com/jmettraux/rufus-scheduler and https://github.com/floraison/fugit, hence my question.

Thanks for all your hard work.

**Comment by philr** [comment]
I'm aware of at least one fundamental difference between `EtOrbi::EoTime` and `TZInfo::LocalTime`. `EoTime` knows the time zone the time relates to. `LocalTime` only has information about the offset observed at the time. This will affect the result of the `#+` and `#-` operators when reaching daylight savings (and other) transitions.

2.0.0 is nearly done. I'm working on a couple of fairly small final changes. I've also been looking at performance, which for some operations has got worse. I think this is mainly due to now setting the offset of the result and the underlying performance of `Time#localtime` and `Time#utc` (so there may not be anything further that can be done).

The availability will depend on how much free time I get. I'd like to think that the final release can be sometime in the next couple of months. I'm not making any promises though.

**Comment by jmettraux** [comment]
Thanks for the information about `TZInfo::LocalTime`. I will then keep et-orbi afloat for the moment.

Best regards.
