### ISSUE TITLE
Timezone support by Time in Ruby 2.6

### ISSUE THREAD

**Issue by nobu** [tzinfo/tzinfo#94]
Built-in `Time` class in Ruby 2.6 is going to support timezone, as [this ticket](https://bugs.ruby-lang.org/issues/14850).
[My patch](https://github.com/nobu/ruby/tree/feature/14850-timezone) works fine with tzinfo 1.2.2, but not with 2.0.0.pre1, because `TZInfo::Timestamp.for` dispatches by its argument's class.
Couldn't you consider to accept a `Time`-like object which have `to_i` method (and maybe `subsec`)?

Thank you.

**Comment by philr** [comment]
Sorry for the delay in responding to this.

I see that you've now [changed `Time::TM` to be a subclass of `Time`](https://github.com/nobu/ruby/commit/def5d87b5e3c0fe661004d455bad85091f401d04). I assume that this is a temporary workaround and not intended to be retained?

I've pushed a new [feature/support_time_tm_struct](https://github.com/tzinfo/tzinfo/tree/feature/support_time_tm_struct) branch with changes to `TZInfo::Timestamp` to handle the `Struct` version of `Time::TM`. I've kept the argument class checking. I prefer this approach because `Timestamp.for` also converts the block result back to the type of the given value.

Note that TZInfo 1.2 is [also checking classes](https://github.com/tzinfo/tzinfo/blob/v1.2.5/lib/tzinfo/time_or_datetime.rb#L17), but falls back to calling `#to_i`. This will cause any sub-second precision to be lost and make methods like `utc_to_local` and `local_to_utc` return an `Integer` instead of a `Time`.

**Comment by nobu** [comment]
Regarding the superclass of `Time::TM`, I'm still wondering what it should be.
@akr, do you have any opinion?

In general, I don't think checking classes is preferred in ruby.
Falling back to calling `#to_i` (and `#subsec` optionally) feels better, or coercing by `#to_time`.

**Comment by akr** [comment]
Time::TM is a internal mechanism of Time.
So, "Time::TM inherits Time" means "Time use Time internally".
I think it is needlessly complex.
So, I vote Time::TM doesn't inherit Time.

**Comment by philr** [comment]
I've committed a [change](https://github.com/tzinfo/tzinfo/commit/32e65c2fdaac37fa494e8e2f87474d679472a360) to master to accept Time-like values (checking that the object responds to both to_i and subsec).

According to https://ruby-doc.org/core-2.6.0.preview3/Time.html#class-Time-label-Timezone+argument, 'the sub-second attributes [of the Time-like object] are fixed as 0', so TZInfo 1.2 only calling `#to_i` should not be an issue.
