### ISSUE TITLE
Africa/Casablanca offset incorrect

### ISSUE THREAD

**Issue by lelelyons** [tzinfo/tzinfo#98]
The offset seems to be incorrect (see below), I believe it should be 3600? Or am I misunderstanding something?

![screenshot 2019-02-06 at 14 04 23](https://user-images.githubusercontent.com/31961970/52346766-45320b00-2a18-11e9-880f-ef3c7458333a.png)

**Comment by philr** [comment]
Your time zone data is probably out of date. Morocco's change to permanent UTC+1 was included in the [2018g](https://mm.icann.org/pipermail/tz-announce/2018-October/000052.html) release of the IANA Time Zone Database. Further changes were made to include fallbacks for Ramadan in [2018h](https://mm.icann.org/pipermail/tz-announce/2018-December/000053.html).

With the latest data, I get the expected result:

```ruby
tz = TZInfo::Timezone.get('Africa/Casablanca')
# => #<TZInfo::DataTimezone: Africa/Casablanca>
tz.current_period.utc_offset
# => 3600
```

If you are using [`ZoneinfoDataSource`](https://www.rubydoc.info/gems/tzinfo/2.0.0/TZInfo/DataSources/ZoneinfoDataSource), check to see if there is an updated tzdata package available for your operating system. Otherwise, you can add [tzinfo-data](https://rubygems.org/gems/tzinfo-data) version 1.2018.7 or later to your Gemfile and use [`RubyDataSource`](https://www.rubydoc.info/gems/tzinfo/2.0.0/TZInfo/DataSources/RubyDataSource).

**Comment by philr** [comment]
The 2018h 'main' definition of Africa/Casablanca uses a base offset of UTC+1 throughout the year and observes negative daylight savings during Ramadan. There is a separate 'rearguard' version of the IANA Time Zone Database that changes this around so that a base offset of UTC+0 is used throughout the year and positive daylight savings is observed at all times other than during Ramadan.

If you are using `ZoneinfoDataSource` and have up to date zoneinfo files built from the 'rearguard' definitions, then `utc_offset` will return 0, but [`utc_total_offset`](https://www.rubydoc.info/gems/tzinfo/1.2.5/TZInfo%2FTimezonePeriod:utc_total_offset) will return 3600 for most of the year.

Note also that `utc_offset` and `utc_total_offset` have been renamed [`base_utc_offset`](https://www.rubydoc.info/gems/tzinfo/2.0.0/TZInfo%2FTimezonePeriod:base_utc_offset) and [`observed_utc_offset`](https://www.rubydoc.info/gems/tzinfo/2.0.0/TZInfo%2FTimezonePeriod:observed_utc_offset) respectively in tzinfo version 2.0.0.

**Comment by dennismonsewicz** [comment]
I am receiving the following error when looking up the Timezone info for `Africa/Casablanca`

```
irb(main):031:0> tz = TZInfo::Timezone.get('Africa/Casablanca')
TZInfo::InvalidTimezoneIdentifier: The first offset indicated by the POSIX-style TZ string did not match the final defined offset in file '/usr/share/zoneinfo/Africa/Casablanca'.
```
